Add retries to vault env hook

diff --git a/agents/hooks/environment b/agents/hooks/environment
--- a/agents/hooks/environment
+++ b/agents/hooks/environment
@@ -2,14 +2,35 @@
 
 set -euo pipefail
 
+retry() {
+  local retries=$1; shift
+  local delay=$1; shift
+  local attempts=1
+
+  until "$@"; do
+    retry_exit_status=$?
+    echo "Exited with $retry_exit_status" >&2
+    if (( retries == "0" )); then
+      return $retry_exit_status
+    elif (( attempts == retries )); then
+      echo "Failed $attempts retries" >&2
+      return $retry_exit_status
+    else
+      echo "Retrying $((retries - attempts)) more times..." >&2
+      attempts=$((attempts + 1))
+      sleep "$delay"
+    fi
+  done
+}
+
 export VAULT_ADDR=https://secrets.elastic.co:8200
 
-VAULT_ROLE_ID="$(gcloud secrets versions access latest --secret=kibana-buildkite-vault-role-id)"
+VAULT_ROLE_ID="$(retry 5 15 gcloud secrets versions access latest --secret=kibana-buildkite-vault-role-id)"
 # export VAULT_ROLE_ID
 
-VAULT_SECRET_ID="$(gcloud secrets versions access latest --secret=kibana-buildkite-vault-secret-id)"
+VAULT_SECRET_ID="$(retry 5 15 gcloud secrets versions access latest --secret=kibana-buildkite-vault-secret-id)"
 # export VAULT_SECRET_ID
 
-vault login -no-print "$(vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")"
+vault login -no-print "$(retry 5 30 vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")"
 
 export DOCKER_BUILDKIT=1
